- name: "Install nginx"
  apt: pkg=nginx state=latest

- name: Remove the default app
  command: rm -rf /etc/nginx/sites-enabled/default

- name: Remove the app's config, if exists
  command: rm -rf /etc/nginx/sites-enabled/default

- name: Remove the app's symlink, if exists
  command: rm -rf /etc/nginx/sites-enabled/ilikeyoureally  

- name: Configure nginx for the app
  template: src=etc_nginx_sites-available_suchgreatheights.conf.j2 dest=/etc/nginx/sites-available/suchgreatheights group=www-data owner=www-data force=yes

- name: Enable the app
  file: src=/etc/nginx/sites-available/suchgreatheights dest=/etc/nginx/sites-enabled/suchgreatheights state=link

- name: Restart nginx
  command: service nginx restart
