- name: "ruby-from-src | ensure directory temporary ruby download directory is present"
  file: state=directory path={{ruby_tmp_dir}}

- name: "ruby-from-src | download ruby source"
  get_url: url={{ruby_url}} dest={{ruby_tmp_dir}}

- name: "ruby-from-src | ensure ruby is extracted"
  command: tar -xzf {{ruby_file}} chdir={{ruby_tmp_dir}} creates={{tmp_ruby_path}}

- name: "ruby-from-src | ensure ruby is configured"
  command: ./configure chdir={{tmp_ruby_path}} creates={{tmp_ruby_path}}/Makefile

- name: "ruby-from-src | ensure ruby is compiled"
  command: make chdir={{tmp_ruby_path}} creates={{tmp_ruby_path}}/ruby

- name: "ruby-from-src | ensure ruby is installed"
  command: make install chdir={{tmp_ruby_path}} creates=/usr/local/bin/ruby
