- name: "Add Ruby repository"
  apt_repository: repo=ppa:brightbox/ruby-ng

- name: Install Ruby 2.5
  apt: pkg=ruby2.5 state=latest update_cache=yes

- name: Install Ruby 2.5 dev package
  apt: pkg=ruby2.5-dev state=latest

- name: Install bundler
  command: gem install bundler
